"""Disclaimer: versioned user acceptance required before any AI analysis."""
from fastapi import APIRouter, Depends, HTTPException
from core.db import db
from core.security import get_current_user, iso, now_utc

router = APIRouter(tags=["disclaimer"])

DISCLAIMER_VERSION = "v1-2026-04"

DISCLAIMER_TEXT = """Neural Stock Intelligence — Analysis Disclaimer

The AI-generated output from Neural (recommendations, price targets, stop losses, reasoning, risk factors, accuracy scorecards, and any shared verdicts) is provided for informational and educational purposes only. It does not constitute financial advice, investment advice, trading advice, or any other sort of professional advice.

1. Not a registered adviser. Neural is not a licensed financial adviser, broker-dealer, or investment adviser. No content on this platform should be construed as a recommendation to buy, sell, or hold any security or asset.

2. Your responsibility. You alone are responsible for any investment decisions you make. You should conduct your own research, consult a qualified professional, and consider your personal financial situation before acting on anything you read here.

3. Markets are volatile. Past performance, historical prices, and AI-generated forecasts do not guarantee future results. Any position may lose value, and you may lose the entire amount invested.

4. Model limitations. Outputs are generated by large language models and quantitative heuristics that can be incomplete, incorrect, or out of date. The data may not reflect market-moving news, corporate events, or real-time conditions.

5. No fiduciary relationship. Using Neural does not create any adviser-client, fiduciary, or professional relationship between you and Neural, its operators, or its affiliates.

6. Jurisdictional limits. Some products, exchanges, or strategies discussed may be restricted or unlawful in your jurisdiction. You are responsible for compliance with all applicable laws and regulations.

7. No liability. To the maximum extent permitted by law, Neural and its affiliates disclaim all liability for direct, indirect, incidental, consequential, or special damages arising from your use of the platform.

By clicking "I understand and accept", you confirm that you have read this disclaimer, understand that all content is for educational use only, and agree to use Neural at your own risk."""


@router.get("/disclaimer")
async def get_disclaimer(user=Depends(get_current_user)):
    return {
        "version": DISCLAIMER_VERSION,
        "text": DISCLAIMER_TEXT,
        "accepted": user.get("disclaimer_accepted_version") == DISCLAIMER_VERSION,
        "accepted_at": user.get("disclaimer_accepted_at"),
    }


@router.post("/disclaimer/accept")
async def accept_disclaimer(user=Depends(get_current_user)):
    await db.users.update_one(
        {"id": user["id"]},
        {"$set": {
            "disclaimer_accepted_version": DISCLAIMER_VERSION,
            "disclaimer_accepted_at": iso(now_utc()),
        }},
    )
    return {"ok": True, "version": DISCLAIMER_VERSION, "accepted_at": iso(now_utc())}


async def require_accepted(user: dict):
    """Raise 428 (Precondition Required) if user has not accepted the current disclaimer."""
    if user.get("disclaimer_accepted_version") != DISCLAIMER_VERSION:
        raise HTTPException(
            status_code=428,
            detail={
                "code": "disclaimer_required",
                "version": DISCLAIMER_VERSION,
                "message": "You must accept the Neural Analysis Disclaimer before running AI analysis.",
            },
        )
