"""Regression test for the LLM provenance badge contract.

The frontend `<LLMProvenanceBadge analysis={...} />` only renders a
"Powered by <model>" footnote when the verdict was NOT generated by the
primary provider (Anthropic). This test locks the backend persistence
path so that:

  1. Successful analyses always have `llm_provider` + `llm_model`
     populated (so a future fallback verdict carries provenance).
  2. The `_public_view` whitelist surfaces these fields on shared pages
     (frontend reads them from the public share endpoint too).
  3. The frontend's `PROVIDER_LABELS` keys stay in sync with the
     provider strings the backend emits — anthropic / gemini / openai.
"""
from __future__ import annotations

import sys
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[1]
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))


def test_public_view_surfaces_llm_provider_and_model():
    """`_public_view` MUST whitelist the provider+model fields, otherwise
    shared verdicts won't show the fallback footnote on PublicVerdictPage."""
    from routers.analysis import _public_view
    sample = {
        "ticker": "AAPL",
        "recommendation": "BUY",
        "confidence_score": 70,
        "executive_summary": "...",
        "llm_provider": "gemini",
        "llm_model": "gemini-2.5-pro",
    }
    out = _public_view(sample)
    assert out.get("llm_provider") == "gemini"
    assert out.get("llm_model") == "gemini-2.5-pro"


def test_public_view_handles_missing_provider_gracefully():
    """Older analyses (pre-feb-2026) won't have llm_provider on the doc.
    `_public_view` MUST surface None, not raise — the frontend treats
    null/missing as 'no badge' which is the correct behaviour for legacy
    rows we have no provenance for."""
    from routers.analysis import _public_view
    out = _public_view({"ticker": "AAPL", "recommendation": "BUY"})
    assert out.get("llm_provider") is None
    assert out.get("llm_model") is None


def test_fallback_chain_provider_keys_match_frontend_label_map():
    """The frontend `PROVIDER_LABELS` map keys MUST cover every provider
    string the backend emits via `_LLM_FALLBACK_CHAIN`. If a new provider
    is added to the chain without updating the frontend map, verdicts
    from that provider would silently skip the badge.

    Reads the JSX file textually because we can't import JS into pytest;
    the assertion is small (substring match for each provider key)."""
    from services.ai import _LLM_FALLBACK_CHAIN
    backend_providers = {entry[0] for entry in _LLM_FALLBACK_CHAIN}

    # Frontend map lives at frontend/src/components/LLMProvenanceBadge.jsx
    fe_path = Path(__file__).resolve().parents[2] / "frontend" / "src" / "components" / "LLMProvenanceBadge.jsx"
    assert fe_path.exists(), f"LLMProvenanceBadge.jsx not found at {fe_path}"
    src = fe_path.read_text()

    # PROVIDER_LABELS is a flat object literal; every backend provider
    # key must appear as a quoted property inside it.
    for prov in backend_providers:
        assert f'{prov}:' in src, (
            f"Frontend PROVIDER_LABELS is missing key '{prov}'. "
            f"Backend chain: {sorted(backend_providers)}. "
            f"Update LLMProvenanceBadge.jsx so verdicts from '{prov}' get a footnote."
        )
