/* eslint-disable max-len */
/**
 * StockDNA — investor type catalogue.
 *
 * 8 types, each with bilingual descriptions (en/id), bilingual trait
 * cards, EN/ID insights, IDX + INTL stock matches, and visual metadata
 * (emoji, colour, risk meter %).
 */

export const TYPES = {
    visionary: {
        ne: "THE VISIONARY", ni: "SI VISIONER", em: "🔭",
        de: "You invest in futures, not just companies. You see where the world is heading before the market prices it in — and you have the conviction to hold paradigm-shifting positions even when others doubt you.",
        di: "Anda berinvestasi di masa depan, bukan hanya perusahaan. Anda melihat ke mana dunia menuju sebelum pasar mencerminkannya, dan Anda memiliki keyakinan untuk memegang posisi revolusioner.",
        risk: 82, re: "HIGH", ri: "TINGGI", color: "#7c3aed",
        tr: [
            { i: "🚀", le: "Style", li: "Gaya", ve: "Moonshot", vi: "Moonshot" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "3–10 Years", vi: "3–10 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Macro Vision", vi: "Visi Makro" },
            { i: "💎", le: "Hold", li: "Hold", ve: "Conviction", vi: "Keyakinan" },
        ],
        si: [
            { t: "NVDA", n: "NVIDIA", e: "AI infrastructure backbone.", i: "Tulang punggung infrastruktur AI." },
            { t: "TSLA", n: "Tesla", e: "Energy + autonomy intersection.", i: "Persimpangan energi + otonomi." },
            { t: "PLTR", n: "Palantir", e: "Data sovereignty & AI-for-gov.", i: "Kedaulatan data & AI untuk pemerintah." },
            { t: "ARKK", n: "ARK Innovation ETF", e: "Basket of disruptors.", i: "Keranjang inovator disruptif." },
            { t: "CRSP", n: "CRISPR Therapeutics", e: "Gene editing as the next platform.", i: "Pengeditan gen sebagai platform berikutnya." },
            { t: "SE", n: "Sea Limited", e: "Southeast Asia's digital ecosystem.", i: "Ekosistem digital Asia Tenggara." },
        ],
        sx: [
            { t: "GOTO", n: "GoTo Gojek Tokopedia", e: "Indonesia's super-app ecosystem.", i: "Ekosistem super-app Indonesia." },
            { t: "BREN", n: "Barito Renewables", e: "Green energy transition play.", i: "Bermain transisi energi hijau." },
            { t: "MDKA", n: "Merdeka Copper Gold", e: "Battery metals: copper, nickel, gold.", i: "Logam baterai: tembaga, nikel, emas." },
            { t: "ARTO", n: "Bank Jago", e: "Digital-first bank backed by GoPay.", i: "Bank digital-first didukung GoPay." },
            { t: "CUAN", n: "Petrindo Jaya Kreasi", e: "Riding the EV metals supercycle.", i: "Mengikuti supersiklus logam EV." },
            { t: "AMMN", n: "Amman Mineral", e: "Indonesia's largest new copper mine.", i: "Tambang tembaga baru terbesar Indonesia." },
        ],
        ie: [
            { s: "Your superpower:", t: "You connect macro dots others miss — and you likely spotted AI before consensus." },
            { s: "Your blindspot:", t: "Conviction without position sizing discipline can be devastating. Even visionaries need risk limits." },
            { s: "Investor archetype:", t: "You share DNA with Cathie Wood and early Peter Lynch. Never bet everything on one idea." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda menghubungkan titik-titik makro yang terlewatkan. Anda mungkin mendeteksi gelombang AI lebih awal." },
            { s: "Kelemahan Anda:", t: "Keyakinan tanpa disiplin ukuran posisi bisa menghancurkan. Tetapkan batas risiko pada nama spekulatif." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan Cathie Wood dan Peter Lynch awal. Jangan pertaruhkan segalanya pada satu ide." },
        ],
    },
    analyst: {
        ne: "THE ANALYST", ni: "SI ANALIS", em: "📊",
        de: "Numbers are your language. You buy cash flows, margins, and moats — not stories. Your edge is doing the work others won't. You rarely lose money on a thesis; you sometimes just lose on timing.",
        di: "Angka adalah bahasa Anda. Anda membeli arus kas, margin, dan keunggulan — bukan cerita. Keunggulan Anda adalah melakukan pekerjaan yang tidak dilakukan orang lain.",
        risk: 55, re: "MODERATE", ri: "MODERAT", color: "#00b894",
        tr: [
            { i: "📐", le: "Style", li: "Gaya", ve: "Deep Research", vi: "Riset Mendalam" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "1–5 Years", vi: "1–5 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Fundamental", vi: "Fundamental" },
            { i: "🔍", le: "Hold", li: "Hold", ve: "Annual Review", vi: "Tinjauan Tahunan" },
        ],
        si: [
            { t: "MSFT", n: "Microsoft", e: "Durable moat, cloud, AI monetization.", i: "Keunggulan bertahan, cloud, monetisasi AI." },
            { t: "V", n: "Visa Inc.", e: "Near-monopoly payment rails.", i: "Jalur pembayaran hampir monopoli." },
            { t: "GOOG", n: "Alphabet", e: "Search + Cloud + Waymo optionality.", i: "Pencarian + Cloud + opsi Waymo." },
            { t: "BRK.B", n: "Berkshire Hathaway", e: "The ultimate quality compounder.", i: "Compounder kualitas tertinggi." },
            { t: "ASML", n: "ASML Holding", e: "EUV monopoly — no substitute exists.", i: "Monopoli EUV — tidak ada penggantinya." },
            { t: "UNH", n: "UnitedHealth", e: "Healthcare with pricing power and scale.", i: "Layanan kesehatan dengan kekuatan harga." },
        ],
        sx: [
            { t: "BBCA", n: "Bank Central Asia", e: "Indonesia's premier bank — strongest CASA ratio.", i: "Bank terbaik Indonesia — rasio CASA terkuat." },
            { t: "ASII", n: "Astra International", e: "Conglomerate with operational excellence.", i: "Konglomerat dengan keunggulan operasional." },
            { t: "UNVR", n: "Unilever Indonesia", e: "40+ years of consistent dividends.", i: "40+ tahun dividen konsisten." },
            { t: "TLKM", n: "Telkom Indonesia", e: "Digital infrastructure with cloud growth.", i: "Infrastruktur digital dengan cloud yang tumbuh." },
            { t: "KLBF", n: "Kalbe Farma", e: "Healthcare essential across Indonesia.", i: "Esensial kesehatan di seluruh Indonesia." },
            { t: "ICBP", n: "Indofood CBP", e: "Pan-Asian FMCG — Indomie feeds a continent.", i: "FMCG pan-Asia — Indomie memberi makan sebuah benua." },
        ],
        ie: [
            { s: "Your superpower:", t: "You rarely overpay. Entry discipline protects you in downturns and generates outsized returns in recoveries." },
            { s: "Your blindspot:", t: "Analysis paralysis is real. Sometimes the best trade is the one you almost talked yourself out of." },
            { s: "Investor archetype:", t: "You share DNA with Warren Buffett and Charlie Munger. Patience plus rigour is your compounding engine." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda jarang membayar terlalu mahal. Disiplin entry melindungi Anda saat penurunan." },
            { s: "Kelemahan Anda:", t: "Kelumpuhan analisis itu nyata. Kadang perdagangan terbaik adalah yang hampir Anda batalkan." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan Warren Buffett dan Charlie Munger. Kesabaran plus kekakuan adalah mesin compounding Anda." },
        ],
    },
    bold: {
        ne: "THE MAVERICK", ni: "SI MAVERICK", em: "⚡",
        de: "You play offense. You're wired for asymmetry — you'd rather swing big and occasionally miss than play safe and watch others win. Your portfolio is a statement about where you think the world is going.",
        di: "Anda bermain ofensif. Anda terprogram untuk asimetri — Anda lebih suka bertaruh besar daripada bermain aman dan melihat orang lain menang.",
        risk: 90, re: "VERY HIGH", ri: "SANGAT TINGGI", color: "#f59e0b",
        tr: [
            { i: "🎯", le: "Style", li: "Gaya", ve: "High Conviction", vi: "Keyakinan Tinggi" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "6m–3 Years", vi: "6b–3 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Contrarian", vi: "Kontarian" },
            { i: "⚡", le: "Hold", li: "Hold", ve: "Tactical", vi: "Taktis" },
        ],
        si: [
            { t: "MSTR", n: "MicroStrategy", e: "Pure Bitcoin treasury — max beta.", i: "Treasury Bitcoin murni — beta maksimum." },
            { t: "RKLB", n: "Rocket Lab", e: "Small satellite launch challenger.", i: "Penantang peluncuran satelit kecil." },
            { t: "IONQ", n: "IonQ", e: "Quantum computing pure play.", i: "Komputasi kuantum murni." },
            { t: "SOFI", n: "SoFi Technologies", e: "Full-stack banking disruptor.", i: "Disruptor perbankan lengkap." },
            { t: "COIN", n: "Coinbase", e: "Regulated crypto infrastructure.", i: "Infrastruktur kripto teregulasi." },
            { t: "SMCI", n: "Super Micro Computer", e: "AI server infrastructure boom.", i: "Boom infrastruktur server AI." },
        ],
        sx: [
            { t: "BUMI", n: "Bumi Resources", e: "High-beta coal — momentum when commodities cycle.", i: "Batu bara beta tinggi — momentum saat komoditas siklus." },
            { t: "ADRO", n: "Adaro Energy", e: "Diversified energy with coal-to-gas transition.", i: "Energi terdiversifikasi dengan transisi batu bara ke gas." },
            { t: "MDKA", n: "Merdeka Copper Gold", e: "Indonesia's battery metals play.", i: "Bermain logam baterai Indonesia." },
            { t: "DSSA", n: "Dian Swastatika", e: "High-growth energy, mining & digital conglomerate.", i: "Konglomerat energi, pertambangan & digital pertumbuhan tinggi." },
            { t: "AMMN", n: "Amman Mineral", e: "Largest new copper mine on the EV supercycle.", i: "Tambang tembaga baru terbesar dalam supersiklus EV." },
            { t: "CUAN", n: "Petrindo Jaya Kreasi", e: "Battery materials from Indonesia's nickel belt.", i: "Material baterai dari sabuk nikel Indonesia." },
        ],
        ie: [
            { s: "Your superpower:", t: "You're comfortable with volatility when others panic-sell. That emotional edge, channelled correctly, compounds wealth." },
            { s: "Your blindspot:", t: "Position sizing is everything. A single overleveraged bet can erase years of gains. Cap high-risk names at 5–10%." },
            { s: "Investor archetype:", t: "You share DNA with early venture capitalists and Paul Tudor Jones. Your edge is courage — protect it with discipline." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda nyaman dengan volatilitas ketika orang lain panik menjual. Keunggulan emosional itu mengkompounding kekayaan jika disalurkan dengan benar." },
            { s: "Kelemahan Anda:", t: "Ukuran posisi adalah segalanya. Satu taruhan overleveraged bisa menghapus bertahun-tahun keuntungan." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan venture capitalist awal dan Paul Tudor Jones. Keberanian adalah keunggulan Anda." },
        ],
    },
    steady: {
        ne: "THE STEADY HAND", ni: "SI TANGAN KOKOH", em: "🌳",
        de: "You invest like you live — with patience, purpose, and a long view. You build wealth the way a tree grows: slowly, deliberately, and for generations. Dividends feel like rewards. Compounding feels like magic.",
        di: "Anda berinvestasi seperti Anda hidup — dengan kesabaran, tujuan, dan pandangan jangka panjang.",
        risk: 28, re: "LOW", ri: "RENDAH", color: "#10b981",
        tr: [
            { i: "🌱", le: "Style", li: "Gaya", ve: "Dividend Growth", vi: "Pertumbuhan Dividen" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "10–30 Years", vi: "10–30 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Discipline", vi: "Disiplin" },
            { i: "💰", le: "Hold", li: "Hold", ve: "Forever", vi: "Selamanya" },
        ],
        si: [
            { t: "JNJ", n: "Johnson & Johnson", e: "62 consecutive dividend increases.", i: "62 kenaikan dividen berturut-turut." },
            { t: "KO", n: "Coca-Cola", e: "Buffett's favourite — global brand, pricing power.", i: "Favorit Buffett — merek global, kekuatan harga." },
            { t: "PG", n: "Procter & Gamble", e: "Brands bought in boom and bust.", i: "Merek yang dibeli saat boom dan bust." },
            { t: "VYM", n: "Vanguard High Div ETF", e: "Diversified quality dividend payers.", i: "Pembayar dividen berkualitas terdiversifikasi." },
            { t: "ABBV", n: "AbbVie", e: "Pharma powerhouse — extraordinary dividend record.", i: "Raksasa farmasi — rekam jejak dividen luar biasa." },
            { t: "PEP", n: "PepsiCo", e: "50+ years of dividend growth.", i: "50+ tahun pertumbuhan dividen." },
        ],
        sx: [
            { t: "BBCA", n: "Bank Central Asia", e: "Decades of consistent dividend growth.", i: "Puluhan tahun pertumbuhan dividen konsisten." },
            { t: "UNVR", n: "Unilever Indonesia", e: "Consumer staples bought every single day.", i: "Kebutuhan pokok yang dibeli setiap hari." },
            { t: "TLKM", n: "Telkom Indonesia", e: "State telecom with reliable dividends.", i: "Telekomunikasi negara dengan dividen andal." },
            { t: "KLBF", n: "Kalbe Farma", e: "Healthcare essential nationwide.", i: "Esensial kesehatan nasional." },
            { t: "INDF", n: "Indofood", e: "Food empire that feeds Indonesia.", i: "Kerajaan makanan yang memberi makan Indonesia." },
            { t: "SMGR", n: "Semen Indonesia", e: "State cement — steady infrastructure demand.", i: "Semen negara — permintaan infrastruktur stabil." },
        ],
        ie: [
            { s: "Your superpower:", t: "You're immune to market noise. While others panic, you're reinvesting dividends and growing your share count." },
            { s: "Your blindspot:", t: "The world changes. Even the steadiest hand must periodically check whether a company's moat is still intact." },
            { s: "Investor archetype:", t: "You share DNA with John Bogle and dividend legend Geraldine Weiss. Time is your most powerful asset." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda kebal terhadap kebisingan pasar. Sementara orang lain panik, Anda menginvestasikan kembali dividen." },
            { s: "Kelemahan Anda:", t: "Dunia berubah. Bahkan tangan paling kokoh pun harus memeriksa apakah keunggulan kompetitif perusahaan masih utuh." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan John Bogle dan legenda dividen Geraldine Weiss. Waktu adalah aset paling kuat Anda." },
        ],
    },
    explorer: {
        ne: "THE EXPLORER", ni: "SI PENJELAJAH", em: "🗺️",
        de: "You invest like you travel — off the beaten path, before the crowds arrive. Emerging markets, frontier sectors, and overlooked niches are your playground. You have global curiosity and patience to wait for the world to catch up.",
        di: "Anda berinvestasi seperti Anda berwisata — di luar jalur biasa, sebelum kerumunan tiba.",
        risk: 72, re: "HIGH", ri: "TINGGI", color: "#f97316",
        tr: [
            { i: "🌍", le: "Style", li: "Gaya", ve: "Global Discovery", vi: "Penemuan Global" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "2–7 Years", vi: "2–7 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Early Mover", vi: "Penggerak Awal" },
            { i: "🗺️", le: "Hold", li: "Hold", ve: "Thesis Driven", vi: "Didorong Tesis" },
        ],
        si: [
            { t: "EEM", n: "iShares MSCI EM", e: "Broad emerging market exposure.", i: "Eksposur pasar berkembang yang luas." },
            { t: "BABA", n: "Alibaba", e: "Chinese e-commerce at distressed valuations.", i: "E-commerce China dengan valuasi tertekan." },
            { t: "NU", n: "Nu Holdings", e: "Brazil's digital bank — 90M+ customers.", i: "Bank digital Brasil — 90M+ pelanggan." },
            { t: "GRAB", n: "Grab Holdings", e: "Southeast Asia's super-app.", i: "Super-app Asia Tenggara." },
            { t: "SHOP", n: "Shopify", e: "Global commerce for the next billion entrepreneurs.", i: "Perdagangan global untuk miliaran pengusaha berikutnya." },
            { t: "VEA", n: "Vanguard Intl ETF", e: "Developed market geographic diversification.", i: "Diversifikasi geografis pasar maju." },
        ],
        sx: [
            { t: "GOTO", n: "GoTo Gojek Tokopedia", e: "Southeast Asia's most important super-app.", i: "Super-app terpenting di Asia Tenggara." },
            { t: "ARTO", n: "Bank Jago", e: "Digital-first banking frontier backed by GoPay.", i: "Frontier perbankan digital-first didukung GoPay." },
            { t: "BANK", n: "Bank Aladin Syariah", e: "Indonesia's digital Islamic banking frontier.", i: "Frontier perbankan syariah digital Indonesia." },
            { t: "BELI", n: "Belibeli.com", e: "Untapped rural Indonesia e-commerce.", i: "E-commerce pedesaan Indonesia yang belum digarap." },
            { t: "CUAN", n: "Petrindo Jaya Kreasi", e: "Battery materials from Indonesia's nickel belt.", i: "Material baterai dari sabuk nikel Indonesia." },
            { t: "CBDK", n: "Ciputra Development", e: "Untapped Indonesian middle-class housing demand.", i: "Permintaan perumahan kelas menengah Indonesia yang belum digarap." },
        ],
        ie: [
            { s: "Your superpower:", t: "You see investment opportunity where others see complexity. That contrarian lens can generate extraordinary returns." },
            { s: "Your blindspot:", t: "Political risk and currency fluctuations can destroy a perfectly timed thesis. Hedge your exposure where possible." },
            { s: "Investor archetype:", t: "You share DNA with Mark Mobius and Jim Rogers. The world is your investment universe — use it wisely." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda melihat peluang investasi di mana orang lain melihat kompleksitas." },
            { s: "Kelemahan Anda:", t: "Risiko politik dan fluktuasi mata uang bisa menghancurkan tesis yang waktunya sempurna." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan Mark Mobius dan Jim Rogers. Dunia adalah semesta investasi Anda." },
        ],
    },
    conservative: {
        ne: "THE GUARDIAN", ni: "SI PENJAGA", em: "🛡️",
        de: "You believe the first rule of investing is: don't lose money. You've worked hard for what you have, and you won't hand it to volatility. Your portfolio is a fortress — built to preserve, grow slowly, and weather every storm.",
        di: "Anda percaya aturan pertama investasi adalah: jangan kehilangan uang.",
        risk: 18, re: "VERY LOW", ri: "SANGAT RENDAH", color: "#6366f1",
        tr: [
            { i: "🛡️", le: "Style", li: "Gaya", ve: "Capital Preservation", vi: "Preservasi Modal" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "5–20 Years", vi: "5–20 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Risk Management", vi: "Manajemen Risiko" },
            { i: "🔒", le: "Hold", li: "Hold", ve: "Quality Only", vi: "Kualitas Saja" },
        ],
        si: [
            { t: "BND", n: "Vanguard Total Bond", e: "Core fixed income anchor.", i: "Jangkar pendapatan tetap utama." },
            { t: "VOO", n: "Vanguard S&P 500", e: "Passive exposure beats 90% of active managers.", i: "Eksposur pasif mengalahkan 90% manajer aktif." },
            { t: "GLD", n: "SPDR Gold", e: "Inflation hedge and safe-haven.", i: "Lindung nilai inflasi dan safe-haven." },
            { t: "SCHD", n: "Schwab US Div ETF", e: "Quality dividends with lower volatility.", i: "Dividen berkualitas dengan volatilitas lebih rendah." },
            { t: "TIP", n: "iShares TIPS ETF", e: "Inflation-protected purchasing power.", i: "Daya beli terlindungi inflasi." },
            { t: "MCD", n: "McDonald's", e: "Recession-resistant — 40+ year dividend.", i: "Tahan resesi — dividen 40+ tahun." },
        ],
        sx: [
            { t: "BBCA", n: "Bank Central Asia", e: "Indonesia's safest bank — lowest NPL in sector.", i: "Bank teraman Indonesia — NPL terendah di sektor." },
            { t: "BMRI", n: "Bank Mandiri", e: "State bank with government backing.", i: "Bank negara dengan dukungan pemerintah." },
            { t: "TLKM", n: "Telkom Indonesia", e: "Defensive revenue — monopoly on national infrastructure.", i: "Pendapatan defensif — monopoli infrastruktur nasional." },
            { t: "UNVR", n: "Unilever Indonesia", e: "Recession-proof consumer brands.", i: "Merek konsumen tahan resesi." },
            { t: "KLBF", n: "Kalbe Farma", e: "Healthcare — always in demand even in downturns.", i: "Kesehatan — selalu ada permintaan bahkan saat penurunan." },
            { t: "SMGR", n: "Semen Indonesia", e: "Government-backed construction — steady demand.", i: "Konstruksi didukung pemerintah — permintaan stabil." },
        ],
        ie: [
            { s: "Your superpower:", t: "Sleeping well is a legitimate investment strategy. Avoiding catastrophic losses is the most powerful form of compounding." },
            { s: "Your blindspot:", t: "Inflation is the silent thief. A too-conservative allocation loses purchasing power slowly over decades." },
            { s: "Investor archetype:", t: "You share DNA with John Templeton in his later years and endowment managers who prioritise capital longevity." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Tidur nyenyak adalah strategi investasi yang sah." },
            { s: "Kelemahan Anda:", t: "Inflasi adalah pencuri diam-diam. Alokasi yang terlalu konservatif kehilangan daya beli secara perlahan." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan John Templeton dan manajer endowmen yang memprioritaskan umur panjang modal." },
        ],
    },
    balanced: {
        ne: "THE STRATEGIST", ni: "SI AHLI STRATEGI", em: "⚖️",
        de: "You've found the middle path most investors spend years searching for. You're neither reckless nor timid. You construct portfolios like an architect: with a plan, balance, and an eye on what stands in 50 years.",
        di: "Anda telah menemukan jalan tengah yang dicari kebanyakan investor selama bertahun-tahun.",
        risk: 50, re: "MODERATE", ri: "MODERAT", color: "#14b8a6",
        tr: [
            { i: "⚖️", le: "Style", li: "Gaya", ve: "Balanced Growth", vi: "Pertumbuhan Seimbang" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "3–15 Years", vi: "3–15 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Portfolio Design", vi: "Desain Portofolio" },
            { i: "🔄", le: "Hold", li: "Hold", ve: "Rebalancing", vi: "Penyeimbangan Ulang" },
        ],
        si: [
            { t: "VTI", n: "Vanguard Total Market", e: "Entire US market — core strategic holding.", i: "Seluruh pasar AS — pegangan strategis utama." },
            { t: "AAPL", n: "Apple", e: "Best brand and ecosystem lock-in.", i: "Merek terbaik dan kunci ekosistem." },
            { t: "JPM", n: "JPMorgan Chase", e: "World's best-run bank.", i: "Bank terbaik dunia." },
            { t: "VXUS", n: "Vanguard Intl ETF", e: "International balance to US concentration.", i: "Keseimbangan internasional terhadap konsentrasi AS." },
            { t: "AMT", n: "American Tower", e: "Global cell tower REIT — inflation-linked.", i: "REIT menara sel global — terkait inflasi." },
            { t: "LLY", n: "Eli Lilly", e: "Healthcare innovation leader.", i: "Pemimpin inovasi kesehatan." },
        ],
        sx: [
            { t: "BBCA", n: "Bank Central Asia", e: "Core IDX anchor — quality and dividend.", i: "Jangkar IDX utama — kualitas dan dividen." },
            { t: "ASII", n: "Astra International", e: "Conglomerate across auto, agri, finance, infra.", i: "Konglomerat di otomotif, agri, keuangan, infrastruktur." },
            { t: "TLKM", n: "Telkom Indonesia", e: "Defensive tech-adjacent state player.", i: "Pemain negara defensif dekat teknologi." },
            { t: "BBRI", n: "Bank Rakyat Indonesia", e: "Micro-lending champion — Indonesia's rural economy.", i: "Juara pinjaman mikro — ekonomi pedesaan Indonesia." },
            { t: "SIDO", n: "Sido Muncul", e: "Herbal healthcare with growing exports.", i: "Kesehatan herbal dengan ekspor yang tumbuh." },
            { t: "INCO", n: "Vale Indonesia", e: "Nickel for Indonesia's battery materials future.", i: "Nikel untuk masa depan material baterai Indonesia." },
        ],
        ie: [
            { s: "Your superpower:", t: "You never make the catastrophic mistake because you never concentrate recklessly. Diversified compounding is historically unbeatable." },
            { s: "Your blindspot:", t: "Balance can mean mediocrity. Designate a 10–15% conviction sleeve for your highest-confidence ideas." },
            { s: "Investor archetype:", t: "You share DNA with David Swensen and the Yale Endowment — asset allocation as the primary return driver." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda tidak pernah membuat kesalahan bencana karena Anda tidak pernah berkonsentrasi sembarangan." },
            { s: "Kelemahan Anda:", t: "Keseimbangan bisa berarti kebiasa-biasaan." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan David Swensen dan Yale Endowment." },
        ],
    },
    patient: {
        ne: "THE TIME LORD", ni: "SI TUAN WAKTU", em: "⏳",
        de: "You understand what most investors never grasp: time is the variable that matters most. You don't just hold stocks — you let them breathe, stumble, and recover. Your portfolio grows while others trade their way to mediocrity.",
        di: "Anda memahami apa yang tidak pernah dipahami kebanyakan investor: waktu adalah variabel yang paling penting.",
        risk: 42, re: "MODERATE-LOW", ri: "MODERAT-RENDAH", color: "#ec4899",
        tr: [
            { i: "⌛", le: "Style", li: "Gaya", ve: "Ultra Long Term", vi: "Jangka Sangat Panjang" },
            { i: "⏳", le: "Horizon", li: "Cakrawala", ve: "10–40 Years", vi: "10–40 Tahun" },
            { i: "🧠", le: "Edge", li: "Keunggulan", ve: "Compounding", vi: "Compounding" },
            { i: "🧘", le: "Hold", li: "Hold", ve: "Never Sell", vi: "Tidak Pernah Jual" },
        ],
        si: [
            { t: "AMZN", n: "Amazon", e: "AWS + commerce + logistics compounding machine.", i: "Mesin compounding AWS + perdagangan + logistik." },
            { t: "MA", n: "Mastercard", e: "Global payment duopoly — extraordinary free cash flow.", i: "Duopoli pembayaran global — arus kas bebas luar biasa." },
            { t: "NVO", n: "Novo Nordisk", e: "GLP-1 obesity drugs reshaping global health.", i: "Obat obesitas GLP-1 merombak kesehatan global." },
            { t: "TSM", n: "TSMC", e: "Semiconductor sovereignty — indispensable to all tech.", i: "Kedaulatan semikonduktor." },
            { t: "COST", n: "Costco", e: "Membership model — loyal customers, predictable cash flows.", i: "Model keanggotaan — pelanggan setia." },
            { t: "DIS", n: "Walt Disney", e: "100-year brand — IP compounding across generations.", i: "Merek 100 tahun — IP mengkompound antar generasi." },
        ],
        sx: [
            { t: "BBCA", n: "Bank Central Asia", e: "Hold-forever IDX quality — 20%+/year for decades.", i: "Kualitas IDX pegang-selamanya." },
            { t: "ASII", n: "Astra International", e: "Indonesia's industrial backbone through every cycle.", i: "Tulang punggung industri Indonesia melalui setiap siklus." },
            { t: "KLBF", n: "Kalbe Farma", e: "Healthcare for 270M growing population.", i: "Layanan kesehatan untuk 270 juta populasi yang tumbuh." },
            { t: "BBRI", n: "Bank Rakyat Indonesia", e: "Micro-credit machine serving Indonesia's 60M+ SMEs.", i: "Mesin kredit mikro melayani 60 juta+ UKM Indonesia." },
            { t: "INDF", n: "Indofood", e: "Food security — growing middle class = growing demand.", i: "Ketahanan pangan." },
            { t: "SMSM", n: "Selamat Sempurna", e: "Auto parts compounder — boring, beautiful, 30+ years.", i: "Compounder suku cadang otomotif." },
        ],
        ie: [
            { s: "Your superpower:", t: "You let the market do the heavy lifting. Every year of patience adds compounding that most investors destroy with trades." },
            { s: "Your blindspot:", t: "Holding forever can mean ignoring disruption. Every 5 years: is this company built to last the next 20?" },
            { s: "Investor archetype:", t: "You share DNA with Buffett's 'favourite holding period is forever' philosophy. You are the market's rarest species." },
        ],
        ii: [
            { s: "Kekuatan Anda:", t: "Anda membiarkan pasar melakukan kerja berat." },
            { s: "Kelemahan Anda:", t: "Memegang selamanya bisa berarti mengabaikan disrupsi." },
            { s: "Arketipe investor:", t: "Anda berbagi DNA dengan filosofi Buffett 'periode penahanan favorit adalah selamanya'." },
        ],
    },
};
